---
version: 2.1
commands:
  print_pipeline_id:
    steps:
      - run: echo ${CIRCLE_WORKFLOW_ID}
jobs:
  print_job:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - print_pipeline_id
workflows:
  print_pipeline_id_workflow:
    jobs:
      - print_job